INSERT INTO usuarios (nome) VALUES ('Diego Dantas Domingues');
INSERT INTO usuarios (nome) VALUES ('Deric Dantas Domingues');
INSERT INTO usuarios (nome) VALUES ('Daniel Cesar Domingues');
INSERT INTO usuarios (nome) VALUES ('João da Silva');
INSERT INTO usuarios (nome) VALUES ('William Costa');
INSERT INTO usuarios (nome) VALUES ('Cleide Aparecida Dantas Domingues');
INSERT INTO usuarios (nome) VALUES ('Guilherme Ferreira Santos');
INSERT INTO usuarios (nome) VALUES ('André Matos da Silva');
INSERT INTO usuarios (nome) VALUES ('Natália Gomes Alves');
INSERT INTO usuarios (nome) VALUES ('Jéssica Alves Campos');
INSERT INTO usuarios (nome) VALUES ('Renata Almeida ');
INSERT INTO usuarios (nome) VALUES ('Luís Lopes');
INSERT INTO usuarios (nome) VALUES ('Letícia Ferreira Costa');
INSERT INTO usuarios (nome) VALUES ('Tiago Almeida');
INSERT INTO usuarios (nome) VALUES ('Pedro Batista');
INSERT INTO usuarios (nome) VALUES ('André Carvalho Borges');
